### ISSUE TITLE
Arquivo ex_115.txt

### ISSUE THREAD

**Issue by GuilhermeLuan** [PedroHenrique-Santos/Curso-Python#2]
O arquivo está vazio e está no formato .txt

**Comment by pedrohenriquebraga** [comment]
> O arquivo está vazio e está no formato .txt

Obrigado vou remover ele!!

**Comment by pedrohenriquebraga** [comment]
Pronto já removi o arquivo.

Muito obrigado por ter colaborado, sua colaboração é **muito importante** e sempre bem vinda!!

### VEJA MAIS SOBRE MIM

 * Acesse meu canal do [YouTube](https://youtube.com/gamesantos)
 * [Playlist](https://www.youtube.com/playlist?list=PLgjMn24Q0KieV-qjUQuhPn4DWmU5DUsAJ) com vídeos de programação no meu canal 
 * Me siga no [Instagram](https://instagram.com/pedro_henriquebraga)
 * Entre no meu [Discord](https://discord.gg/626zVxa)
 * Veja Meu [LinkedIn](https://www.linkedin.com/in/pedro-henrique-3214251a4)

![Bye Bye!!](https://user-images.githubusercontent.com/62728884/78843508-576f5680-79d9-11ea-9f55-b618848ae94d.gif)
